name: Request Cloudforet Email
description: Request Cloudforet Email (your_email@cloudforet.io)
labels: [New]
body:
- type: input
  attributes:
    label: Your email address
    description: Provide your requested email addresss
    placeholder: your_name@cloudforet.io
  validations:
    required: true
- type: input
  attributes:
    label: Your real email address
    description: Provide your real email address for forwarding
    placeholder: your_name@gmail.com
  validations:
    required: true
